# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# Site settings
title: Web Data
email: dret@ca.com
description: > # this means to ignore newlines until "baseurl:"
  How to publish data on the Web.
  Web Data principles help you to be open and webby.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://webdata.systems" # the base hostname & protocol for your site
twitter_username: dret
github_username:  dret

# Build settings
markdown: kramdown
theme: jekyll-swiss
theme_color: yellow

# !!! This section is sepcific for the jekyll-swiss theme !!!
# Optional social link, you can choose from the following options:
# twitter (default), instagram, medium, or dribbble
social_link: twitter
social_username: dret
github_repo: webdata
